;; -*- mode: eask; lexical-binding: t -*-

(package "ink-mode"
         "0.4.0"
         "Major mode for writing interactive fiction in Ink")

(website-url "https://github.com/Kungsgeten/ink-mode")
(keywords "languages" "wp" "hypermedia")

(package-file "ink-mode.el")
(files "ink-mode.el"
       "test"
       "snippets"
       "doc"
       "README.org"
       "COPYING")

(source "gnu")

(depends-on "emacs" "29.1")

(development
 (depends-on "ert-runner")
 (depends-on "package-lint"))
